import { QueryProvider } from "../(app)/providers";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <main className="mx-auto justify-center max-w-xl flex-col">
          <QueryProvider>{children}</QueryProvider>
        </main>
      </body>
    </html>
  );
}
