import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="mx-auto justify-center max-w-xl flex-col text-gray-900">
          <h1 className="text-red-500 bold">MoovyZoo</h1>
          <p>Where movies goers can stay</p>
          {children}
        </main>
      </body>
    </html>
  );
}
