// Profile-specific error codes
export enum ProfileErrorCode {
  // Profile validation errors
  PROFILE_INVALID_DISPLAY_NAME = "PROFILE_INVALID_DISPLAY_NAME",
  PROFILE_INVALID_AVATAR_URL = "PROFILE_INVALID_AVATAR_URL",
  PROFILE_INVALID_GENRES = "PROFILE_INVALID_GENRES",
  PROFILE_INVALID_PRIVACY_SETTINGS = "PROFILE_INVALID_PRIVACY_SETTINGS",

  // Profile operation errors
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_CREATION_FAILED = "PROFILE_CREATION_FAILED",
  PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED",
  PROFILE_DELETE_FAILED = "PROFILE_DELETE_FAILED",

  // Database errors
  PROFILE_DATABASE_ERROR = "PROFILE_DATABASE_ERROR",
  PROFILE_PERMISSION_DENIED = "PROFILE_PERMISSION_DENIED",

  // Generic errors
  PROFILE_UNKNOWN_ERROR = "PROFILE_UNKNOWN_ERROR",
}

// Re-export common error codes from auth feature
export { AppErrorCode } from "../../../utils/error-codes";
