export interface AppError {
  title: string;
  message: string;
}

export enum AppErrorCode {
  // Authentication errors
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_EMAIL = "AUTH_INVALID_EMAIL",
  AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_WRONG_PASSWORD = "AUTH_WRONG_PASSWORD",
  AUTH_TOO_MANY_REQUESTS = "AUTH_TOO_MANY_REQUESTS",
  AUTH_NETWORK_ERROR = "AUTH_NETWORK_ERROR",
  AUTH_REQUIRES_RECENT_LOGIN = "AUTH_REQUIRES_RECENT_LOGIN",
  AUTH_INVALID_CREDENTIAL = "AUTH_INVALID_CREDENTIAL",
  AUTH_USER_DISABLED = "AUTH_USER_DISABLED",
  AUTH_OPERATION_NOT_ALLOWED = "AUTH_OPERATION_NOT_ALLOWED",

  // Profile errors
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED",
  PROFILE_CREATION_FAILED = "PROFILE_CREATION_FAILED",
  PROFILE_INVALID_DATA = "PROFILE_INVALID_DATA",
  PROFILE_UNAUTHORIZED = "PROFILE_UNAUTHORIZED",
  PROFILE_AVATAR_INVALID = "PROFILE_AVATAR_INVALID",
  PROFILE_DISPLAY_NAME_TAKEN = "PROFILE_DISPLAY_NAME_TAKEN",
  PROFILE_DELETE_FAILED = "PROFILE_DELETE_FAILED",
  PROFILE_INVALID_DISPLAY_NAME = "PROFILE_INVALID_DISPLAY_NAME",

  // Privacy errors
  PRIVACY_UPDATE_FAILED = "PRIVACY_UPDATE_FAILED",
  PRIVACY_INVALID_SETTINGS = "PRIVACY_INVALID_SETTINGS",

  // Validation errors
  VALIDATION_INVALID_EMAIL = "VALIDATION_INVALID_EMAIL",
  VALIDATION_INVALID_PASSWORD = "VALIDATION_INVALID_PASSWORD",
  VALIDATION_INVALID_DISPLAY_NAME = "VALIDATION_INVALID_DISPLAY_NAME",
  VALIDATION_INVALID_AVATAR_URL = "VALIDATION_INVALID_AVATAR_URL",
  VALIDATION_INVALID_GENRES = "VALIDATION_INVALID_GENRES",
  VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",

  // Database errors
  DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR",
  DATABASE_PERMISSION_DENIED = "DATABASE_PERMISSION_DENIED",
  DATABASE_QUOTA_EXCEEDED = "DATABASE_QUOTA_EXCEEDED",
  DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE",

  // Generic errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  AUTH_EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
}
